version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pharmacy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: as798520
      MYSQL_DATABASE: pharmacy_db
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: pharmacy-app
    restart: always
    depends_on:
      - db
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    command: ["java", "-jar", "-Dspring.profiles.active=prod", "app.jar"]

volumes:
  db_data:
