name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect & Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/pharmacy1
            sudo git fetch origin master
            sudo git reset --hard origin/master
            sudo ln -s /usr/bin/docker-compose /usr/local/bin/docker-compose || true
            sudo docker-compose down
            sudo docker-compose up -d --build
